"""Shared pAIper report branding for export formats."""

from __future__ import annotations

from ..report import ReviewReport

GENERATED_BY = "Generated by pAIper"
PAIPER_REPO_LABEL = "pozapas/pAIper"
PAIPER_REPO_URL = "https://github.com/pozapas/pAIper"
GITHUB_ICON_URL = "https://github.githubassets.com/favicons/favicon.svg"
SEP = "\u00b7"


def usage_suffix(r: ReviewReport) -> str:
    tok = r.prompt_tokens + r.completion_tokens
    cost = f"~${r.cost_usd:.3f}" if r.cost_usd is not None else "n/a"
    return f"{r.created_at[:19]}Z {SEP} {tok:,} tokens {SEP} {r.n_calls} calls {SEP} cost {cost}"


def markdown_footer(r: ReviewReport) -> str:
    return (
        f"_{GENERATED_BY} {SEP} GitHub: [{PAIPER_REPO_LABEL}]({PAIPER_REPO_URL}) "
        f"{SEP} {usage_suffix(r)}_"
    )


def plain_footer(r: ReviewReport) -> str:
    return f"{GENERATED_BY} {SEP} GitHub: {PAIPER_REPO_LABEL} ({PAIPER_REPO_URL}) {SEP} {usage_suffix(r)}"


def pdf_footer_html(r: ReviewReport) -> str:
    return (
        f'{GENERATED_BY} {SEP} '
        f'<font color="#ff9f43">GitHub:</font> '
        f'<a href="{PAIPER_REPO_URL}">{PAIPER_REPO_LABEL}</a> {SEP} '
        f'{usage_suffix(r)}'
    )
