"""Render a ReviewReport to a clean, self-contained Markdown report."""

from __future__ import annotations

from ..report import ReviewReport

_SEV_EMOJI = {"CRITICAL": "🔴", "MAJOR": "🟠", "MINOR": "🟡", "PRAISE": "🟢"}
_STATUS_EMOJI = {"PASS": "✅", "FAIL": "❌", "UNCLEAR": "⚠️", "NA": "➖"}
_CITE_EMOJI = {"VERIFIED": "✅", "NOT_FOUND": "❌", "MISMATCH": "⚠️",
               "UNPARSEABLE": "❓", "UNCHECKED": "➖"}


def _bar(score: float) -> str:
    filled = round(score)
    return "█" * filled + "░" * (10 - filled)


def report_to_markdown(r: ReviewReport) -> str:
    L: list[str] = []
    a = L.append

    a(f"# Review Report — {r.title}")
    a("")
    a(f"> **Recommendation: {r.recommendation}**  ·  Overall score **{r.overall_score:.1f}/10**")
    if r.verdict:
        a(f">")
        a(f"> {r.verdict}")
    a("")
    meta = [f"Model: `{r.model}`", f"Depth: {r.depth}"]
    if r.venue_id:
        meta.append(f"Venue: {r.venue_id}")
    meta.append(f"Parser: {r.parse_engine}")
    a("`" + "`  ·  `".join(meta) + "`")
    a("")

    if r.headline_summary:
        a("## Summary")
        a(r.headline_summary)
        a("")

    # scorecard
    a("## Scorecard")
    a("")
    a("| Dimension | Score | |")
    a("|---|---|---|")
    for d in r.dimensions:
        a(f"| {d.label} | {d.score:.1f}/10 | `{_bar(d.score)}` |")
    a("")

    counts = r.counts_by_severity()
    a(f"**Findings:** {_SEV_EMOJI['CRITICAL']} {counts['CRITICAL']} critical · "
      f"{_SEV_EMOJI['MAJOR']} {counts['MAJOR']} major · "
      f"{_SEV_EMOJI['MINOR']} {counts['MINOR']} minor · "
      f"{_SEV_EMOJI['PRAISE']} {counts['PRAISE']} strengths")
    a("")

    if r.strengths:
        a("## Strengths")
        for s in r.strengths:
            a(f"- {s}")
        a("")
    if r.weaknesses:
        a("## Key Weaknesses")
        for w in r.weaknesses:
            a(f"- {w}")
        a("")

    # action plan
    if r.action_items:
        a("## Action Plan (prioritized)")
        for i, it in enumerate(r.action_items, 1):
            a(f"{i}. {_SEV_EMOJI.get(it.priority, '•')} **[{it.priority}]** {it.text}")
        a("")

    # venue fit
    if r.venue_fit:
        v = r.venue_fit
        a(f"## Venue Fit — {v.venue_name}")
        a(f"**Fit score: {v.fit_score}/100**")
        if v.scope_rationale:
            a("")
            a(v.scope_rationale)
        if v.rejection_risks:
            a("")
            a("**Top rejection risks:**")
            for risk in v.rejection_risks:
                a(f"- {risk}")
        if v.checklist:
            a("")
            label = " (model-generated)" if v.checklist_generated else ""
            a(f"**Submission checklist{label}:**")
            a("")
            for c in v.checklist:
                em = _STATUS_EMOJI.get(c.status, "•")
                line = f"- {em} **{c.status}** — {c.text}"
                a(line)
                if c.note:
                    a(f"    - _{c.note}_")
        a("")

    # citations
    if r.citation_check and r.citation_check.enabled:
        cc = r.citation_check
        a("## Citation Verification")
        a(f"Checked **{cc.n_refs}** references · ✅ {cc.n_verified} verified · "
          f"⚠️ {cc.n_suspicious} need attention")
        if cc.note:
            a("")
            a(f"_{cc.note}_")
        sus = [c for c in cc.items if c.status in ("NOT_FOUND", "MISMATCH")]
        if sus:
            a("")
            a("**References needing attention:**")
            for c in sus:
                em = _CITE_EMOJI.get(c.status, "•")
                a(f"- {em} **{c.status}** — {c.title or c.raw[:120]}")
                if c.note:
                    a(f"    - _{c.note}_")
        a("")

    # detailed findings
    a("## Detailed Findings")
    a("")
    for d in r.dimensions:
        a(f"### {d.label} — {d.score:.1f}/10")
        if d.error:
            a(f"_Could not evaluate: {d.error}_")
            a("")
            continue
        if d.summary:
            a(d.summary)
            a("")
        for f in d.findings:
            em = _SEV_EMOJI.get(f.severity, "•")
            a(f"#### {em} [{f.severity}] {f.title}")
            if f.evidence:
                a(f"> {f.evidence}")
            if f.issue:
                a(f"{f.issue}")
            if f.recommendation:
                a(f"**Fix:** {f.recommendation}")
            a("")

    if r.warnings:
        a("## Notes")
        for w in r.warnings:
            a(f"- ⚠️ {w}")
        a("")

    a("---")
    tok = r.prompt_tokens + r.completion_tokens
    cost = f"~${r.cost_usd:.3f}" if r.cost_usd is not None else "n/a"
    a(f"_Generated by AI Paper Reviewer · {r.created_at[:19]}Z · "
      f"{tok:,} tokens · {r.n_calls} calls · cost {cost}_")
    return "\n".join(L)
